name: Testing JS App
on: [push, pull_request]
defaults:
  run:
    shell: bash
    working-directory: js-app-1
jobs:
  tests:
    name: Yarn install dependencies and run tests on ${{ matrix.operating-system }})
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, self-hosted] # , windows-latest, macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: run tests
        run: CI=true yarn test